name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  FLEXVM_APP_ID:  # id of input
    description: 'FlexVM Application ID'
    required: true
    default: ''
  FLEXVM_PASSWORD:  # id of input
    description: 'FlexVM Password'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
